### ISSUE TITLE
what would be

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/parsers#1]
whats the idea you have mention in the issue before? Because I don't like very much current api. Maybe we should use singleton class and `.use`-style.

I see something like this one started before 2-3 months `github.com/jstransformers`, which also don't like and looks ugly in core but powerful. Seems there have some move last month

**Comment by tunnckoCore** [comment]
hmmm.. but you already have https://github.com/jonschlinkert/parser-cache .. soo whats the diffs?

they seems in same age 6-7-8months.

**Comment by tunnckoCore** [comment]
some help with todos? haha

**Comment by jonschlinkert** [comment]
fuccccckckkk. you're killing me dude.

did you actually even look at the code in the two modules? they aren't even similar at all.

**Comment by tunnckoCore** [comment]
ahhahaha, yea i re-review now again parser-cache ;d

**Comment by tunnckoCore** [comment]
nevermind, I dont see so much diffs. both are "like consolidate.js but for parsers", just one have this `.use`-style in case `.register`.

**Comment by jonschlinkert** [comment]
no, one of them actually **HAS** parsers, like consolidate. the other one is an object cache for managing parsers. The first could probably use the second as a dep, but they are not at all the same

**Comment by tunnckoCore** [comment]
exactly

**Comment by jonschlinkert** [comment]
I'd love to see you create an issue to tell tj that styl and stylus and rework are duplicates lol

**Comment by tunnckoCore** [comment]
and dont like this `consolidate` approach for custom adding some parsers. its better to have `.register/.use`

**Comment by tunnckoCore** [comment]
xhahxahxha I will go open :(

**Comment by jonschlinkert** [comment]
I really wouldn't I was just kidding

**Comment by tunnckoCore** [comment]
yea, know

**Comment by jonschlinkert** [comment]
> dont like this consolidate approach for custom adding some parsers.

do you think it might be possible that you're missing some crucial details about the two? Maybe, how they might be used?

**Comment by tunnckoCore** [comment]
mm yea **noticed** that, lower deps, bigger perf

**Comment by jonschlinkert** [comment]
After I post this next thing, don't say "yea I know", just learn something.

**Comment by jonschlinkert** [comment]
## .use

Here we are explicitly defining a plugin chain. 
- Whatever files were defined will be run through this stack. 
- We could add logic inside the plugins to selectively filter which files are parsed, but to some degree that goes against this pattern.

``` js
app
 .use(foo())
 .use(bar())
```

## .register

Here we defining parsers that are associated with specific file extensions, so that parsers are only used on matching files.

``` js
// only parse markdown files
parsers.register('md', function(str) {
  // do stuff to string
});

// only parse hbs files
parsers.register('hbs', function(str) {
  // do stuff to string
});
```

**Comment by tunnckoCore** [comment]
haha, okey this wasn't needed. I already seen `koa`, `express`, `handlebars`, `plugins` and `ware` for the last year.
